
proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  container-backend: kubernetes
  kubernetes:
    internal-networking: true
    url: http://localhost:8001
    image-pull-secret: acr-auth
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
  - id: hello_world
    container-image: <ACR.azurecr.io>/shinyapp

logging:
  file:
    shinyproxy.log
